### ISSUE TITLE
False positive report on issue

### ISSUE THREAD

**Issue by vdbaan** [albinowax/ActiveScanPlusPlus#6] opened 2016-06-23 12:37 UTC
The scan instructs the first request to sleep for 0 seconds and the second for 10 seconds. It does not check if the received responses are valid. 
I discovered this with an application that at irregular intervals gave socket timeout problems which meant that there was no response at all.

**Comment by albinowax** [comment] 2016-06-23 12:47
Occasional false positives caused by irregular network latency are more or less unavoidable with timing-based scans. I could refuse to create issues with empty responses but this may cause some false negatives - sleep() statements could cause network timeouts if they get executed multiple times. I could alternatively send more confirmation requests but this will just slow things down.

I'm not sure there is a clean solution to this.

**Comment by vdbaan** [comment] 2016-06-23 13:37
true, irregular network latency can be a problem. However I do believe that you need an actual response to be able to classify an issue. My problem (and that was also the reason I reported it as an issue) was that both the first and the second request had no response at all (and with this particular application that happened 135 times). 
Perhaps an idea would be to drop the issue if the first request was empty as there is no actual baseline to compare against.

**Comment by albinowax** [comment] 2016-06-23 13:46
It doesn't technically matter if the baseline "don't sleep" response is empty, because all I need to baseline is the time. However I think it should be safe to discard issues when the baseline response is empty - I can't see that happening in an application that's actually working.

**Comment by vdbaan** [comment] 2016-06-23 13:51
An application that doesn't respond has way more other issues to start with.

**Comment by albinowax** [comment] 2016-06-23 14:21
Yeah, I'll hack in a fix in a bit.

**Comment by vdbaan** [comment] 2016-06-23 14:37
(y)

**Comment by albinowax** [comment] 2016-06-28 08:51
This should be fixed now: https://github.com/albinowax/ActiveScanPlusPlus/commit/f124f77a26ff4377b35bb4096cdb33d6b07860fa

**Closed by albinowax** 2016-06-28 08:51 UTC
